services:
  # Service Discovery
  service-registry:
    image: consul:1.14
    container_name: service-registry
    ports:
      - "8500:8500"
    networks:
      - microservice-network

  # Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - microservice-network

  # Redis for Cart Service
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - microservice-network

  # Database
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shopdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - microservice-network

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    command: start-dev
    restart: always
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/shopdb
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - microservice-network

  # API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - USER_SERVICE_URL=http://user-service:3001
      - PRODUCT_SERVICE_URL=http://product-service:3002
      - ORDER_SERVICE_URL=http://order-service:3003
      - CART_SERVICE_URL=http://cart-service:3004
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=shop-realm
      - KEYCLOAK_CLIENT_ID=api-gateway
      - KEYCLOAK_CLIENT_SECRET=LKfwFVt3TvEP7Egd5szY83RbfQ7DDPQN
    depends_on:
      - keycloak
      - user-service
      - product-service
      - order-service
      - cart-service
    networks:
      - microservice-network

  # User Service
  user-service:
    build: ./user-service
    container_name: user-service
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shopdb
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=shop-realm
      - KEYCLOAK_CLIENT_ID=user-service
      - KEYCLOAK_CLIENT_SECRET=LKfwFVt3TvEP7Egd5szY83RbfQ7DDPQN
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
      - keycloak
    networks:
      - microservice-network

  # Product Service
  product-service:
    build: ./product-service
    container_name: product-service
    restart: always
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shopdb
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - JWT_SECRET=your_jwt_secret_key
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - microservice-network
      
  # Order Service
  order-service:
    build: ./order-service
    container_name: order-service
    restart: always
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shopdb
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - JWT_SECRET=your_jwt_secret_key
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - PRODUCT_SERVICE_URL=http://product-service:3002
      - PAYMENT_GATEWAY_URL=http://api-gateway:8000/api/payments
    depends_on:
      - postgres
      - rabbitmq
      - product-service
    networks:
      - microservice-network
      
  # Cart Service
  cart-service:
    build: ./cart-service
    container_name: cart-service
    restart: always
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your_jwt_secret_key
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - PRODUCT_SERVICE_URL=http://product-service:3002
    depends_on:
      - redis
      - rabbitmq
      - product-service
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge

volumes:
  pgdata: